# Generated by Django 5.2.4 on 2025-07-30 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('adhar_no', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('math_10', models.IntegerField()),
                ('science_10', models.IntegerField()),
                ('english_10', models.IntegerField()),
                ('hindi_10', models.IntegerField()),
                ('physics_12', models.IntegerField()),
                ('chemistry_12', models.IntegerField()),
                ('math_12', models.IntegerField()),
                ('branch_1', models.CharField(max_length=50)),
                ('branch_2', models.CharField(max_length=50)),
                ('rank', models.IntegerField(default=0)),
                ('is_allotted', models.BooleanField(default=False)),
                ('allotted_branch', models.CharField(blank=True, max_length=50)),
                ('fee_paid', models.BooleanField(default=False)),
                ('offer_letter_generated', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentDetails',
        ),
    ]
