# Generated by Django 5.2.4 on 2025-08-07 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_studentdetail_chemistry_12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='Percentage',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='allotted_branch',
            field=models.CharField(blank=True, choices=[('', 'Waiting'), ('CSE', 'Computer Science'), ('ECE', 'Electronics'), ('ME', 'Mechanical'), ('CE', 'Civil')], default='', max_length=50, verbose_name='allotted_branch'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='fee_paid',
            field=models.CharField(blank=True, choices=[('', 'Waiting'), ('CSE', 'Computer Science'), ('ECE', 'Electronics'), ('ME', 'Mechanical'), ('CE', 'Civil')], default='', max_length=50, verbose_name='is_paid'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='is_allotted',
            field=models.CharField(blank=True, choices=[('', 'Waiting'), ('NO', 'NO'), ('YES', 'YES'), ('COMMING', 'COMMING')], default='', max_length=50, verbose_name='allotted_branch'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='offer_letter_generated',
            field=models.CharField(blank=True, choices=[('', 'Waiting'), ('NO', 'NO'), ('YES', 'YES'), ('COMMING', 'COMMING')], default='', max_length=50, verbose_name='allotted_branch'),
        ),
    ]
