# Generated by Django 5.2.4 on 2025-08-07 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_studentdetail_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetail',
            old_name='Percentage',
            new_name='Percentage_10',
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='Percentage_12',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='fee_paid',
            field=models.CharField(blank=True, choices=[('', 'Waiting'), ('NO', 'NO'), ('YES', 'YES'), ('COMMING', 'COMMING')], default='', max_length=50, verbose_name='fee_paidd'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='is_allotted',
            field=models.CharField(blank=True, choices=[('', 'Waiting'), ('NO', 'NO'), ('YES', 'YES'), ('COMMING', 'COMMING')], default='', max_length=50, verbose_name='is_allotted'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='offer_letter_generated',
            field=models.CharField(blank=True, choices=[('', 'Waiting'), ('NO', 'NO'), ('YES', 'YES'), ('COMMING', 'COMMING')], default='', max_length=50, verbose_name='offer_letter_generated'),
        ),
    ]
