# Generated by Django 5.2.4 on 2025-08-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_percentage_studentdetail_percentage_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='allotted_branch',
            field=models.CharField(blank=True, choices=[('', 'Waiting'), ('CSE', 'Computer Science'), ('ECE', 'Electronics'), ('ME', 'Mechanical'), ('CE', 'Civil')], default='', max_length=50, verbose_name='Allotted Branch'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='fee_paid',
            field=models.CharField(blank=True, choices=[('', 'Waiting'), ('NO', 'NO'), ('YES', 'YES'), ('COMMING', 'COMMING')], default='', max_length=50, verbose_name='Fee Paid'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='is_allotted',
            field=models.CharField(blank=True, choices=[('', 'Waiting'), ('NO', 'NO'), ('YES', 'YES'), ('COMMING', 'COMMING')], default='', max_length=50, verbose_name='Is Allotted'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='offer_letter_generated',
            field=models.CharField(blank=True, choices=[('', 'Waiting'), ('NO', 'NO'), ('YES', 'YES'), ('COMMING', 'COMMING')], default='', max_length=50, verbose_name='Offer Letter Generated'),
        ),
    ]
