# Generated by Django 5.2.4 on 2025-08-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_studentdetail_allotted_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='course_opted',
            field=models.CharField(blank=True, choices=[('', 'NOT CHOSEN'), ('MCA', 'MCA'), ('BCA', 'BCA'), ('B-TECH', 'B-TECH')], default='', max_length=50, verbose_name='Course Opted'),
        ),
    ]
