# Generated by Django 5.2.4 on 2025-08-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_studentdetail_course_opted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='name',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='phone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
