# Generated by Django 5.2.4 on 2025-08-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_studentdetail_email_remove_studentdetail_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
