# Generated by Django 5.2.4 on 2025-08-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_adminprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
