# Generated by Django 5.2.4 on 2025-08-22 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_adminprofile_email_adminprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
    ]
