# Generated by Django 5.2.4 on 2025-08-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_customuser_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
    ]
