# Generated by Django 5.2.4 on 2025-08-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_registeredstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='fee_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='fee_receipts/', verbose_name='Fee Receipt'),
        ),
    ]
