# Generated by Django 5.2.4 on 2025-08-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_studentdetail_fee_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
