# Generated by Django 5.2.5 on 2025-09-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_studentdetail_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetail',
            name='offer_letter_generated',
        ),
    ]
