# Generated by Django 5.2.4 on 2025-12-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_studentdetail_offer_letter_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
