# Generated by Django 5.2.4 on 2025-12-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_studentdetail_address_alter_studentdetail_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='dob',
            field=models.DateField(),
        ),
    ]
