# Generated by Django 5.2.4 on 2025-12-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_studentsignup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='StudentSignup',
        ),
    ]
