# Generated by Django 5.2.4 on 2025-12-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_studentdetail_address_alter_studentdetail_dob_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisteredStudent',
        ),
    ]
